---
cog_bundle_version: 4
name: victorops
description: Commands for interacting with VictorOps
version: 0.2.3
docker:
  image: cagedata/victorops-cog
  tag: 0.2.3
commands:
  ack:
    executable: "/home/bundle/cog-command"
    description: Ack an open incident
    arguments: "[incident]"
    rules:
    - allow
